# Generated by Django 4.0 on 2021-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211124_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Финальная цена корзина'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Финальная цена товара'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в корзине'),
        ),
    ]
