# Generated by Django 4.0 on 2022-01-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_basketproduct_user_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_custoomer', to='app.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='get_order_date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='make_order_date',
            field=models.DateTimeField(max_length=15),
        ),
    ]
