# Generated by Django 4.0 on 2022-01-17 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_orders_alter_order_get_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=65, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='get_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='make_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время составления заказа'),
        ),
    ]
