# Generated by Django 3.2.3 on 2021-11-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Финальная цена'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
